let mockEmployees = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane@example.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 3,
    firstName: "Alex",
    lastName: "Brown",
    email: "alex@example.com",
    department: "Sales",
    role: "Executive",
  },
  {
    id: 4,
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 5,
    firstName: "Bob",
    lastName: "Williams",
    email: "bob.williams@example.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 6,
    firstName: "Clara",
    lastName: "Lee",
    email: "clara.lee@example.com",
    department: "Marketing",
    role: "Executive",
  },
  {
    id: 7,
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 8,
    firstName: "Ella",
    lastName: "Martinez",
    email: "ella.martinez@example.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 9,
    firstName: "Nikhil",
    lastName: "Sharma",
    email: "nikhil.sharma@example.com",
    department: "IT",
    role: "Intern",
  },
  {
    id: 10,
    firstName: "Olivia",
    lastName: "Brown",
    email: "olivia.brown@example.com",
    department: "Operations",
    role: "Coordinator",
  },
];

